version: '3.4'
services:
  golang:
    image: golang:1.12
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app

  aws:
    image: contino/aws-cli:1.16.116
    env_file: .env
    working_dir: /opt/app
    volumes:
      - ~/.aws:/root/.aws
      - .:/opt/app

  gauth:
    image: contino/aws-google-auth:0.0.28
    env_file: .env
    volumes:
      - ~/.aws:/root/.aws
