AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Musketeers Lambda Go SAM

Parameters:
  StageName:
    Type: String
    AllowedValues:
      - dev
      - qa
      - prod
  EchoMessage:
    Type: String

Globals:
  Function:
    Runtime: go1.x
    
Resources:
  Echo:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub ${AWS::StackName}-echo
      Description: returns the value of environment variable ECHO_MESSAGE
      MemorySize: 128
      CodeUri: ./bin/echo
      Handler: echo
      Policies: 
        - AWSLambdaFullAccess
      Environment:
        Variables:
          ECHO_MESSAGE: !Ref EchoMessage
      Events:
        Get:
          Type: Api
          Properties:
            Method: GET
            Path: /echo
  APIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ServerlessRestApi.Deployment
      RestApiId: !Ref ServerlessRestApi
      StageName: !Ref StageName

Outputs:
    EchoApi:
      Description: "API Gateway endpoint URL for Echo function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/echo/"